import type { Locale } from '@/api/types'

/**
 * 全部界面文案，中英双语（CLAUDE.md 第 11 节：文案集中放这里，不散落在组件里）。
 *
 * 中文是主语言，英文**不是直译** —— 这个产品卖的就是好笑，
 * 逐字翻过去的英文会变成一份说明书。两边各自按各自的语感写。
 *
 * 类型上用 `typeof zh` 卡住 en：漏一个 key 就编译不过，不会出现半中半英的界面。
 */

const zh = {
  appName: '厕评',
  appNameLatin: 'pooping',
  tagline: '厕所版大众点评',
  domain: 'pooping.me',

  // —— 地图页
  nearby: '附近的厕所',
  locating: '正在定位…',
  locationDenied: '拿不到定位，先给你看个默认位置',
  searchThisArea: '搜这片区域',
  recenter: '回到我的位置',
  noResults: '这一带还没有收录的厕所',
  noResultsHint: '把地图拖远点，或者松掉几个筛选',
  resultCount: (n: number) => `${n} 个坑位`,
  listView: '列表',
  mapView: '地图',

  // —— 筛选
  filters: '筛选',
  filterHasPaper: '有纸',
  filterFree: '免费',
  filterAccessible: '无障碍',
  filterSeated: '坐便',
  clearFilters: '清空',

  viewDetail: '查看详情',
  tagsOther: '其它',

  // —— 写评价的两种方式
  modeSelf: '我自己写',
  selfWriteLabel: '想说点什么',
  selfWritePlaceholder: '直接写，不经过 AI',
  selfWriteHint: '不经过 AI，也不会挂「AI 润色」标',
  needSelfText: '还没写呢',
  humanBadge: '本人手写',
  tagCount: (n: number, max: number) => `已选 ${n}/${max}`,
  tagLimitNote: '单选那几组不占名额',
  sortLabel: '排序',
  sortDistance: '距离',
  sortRating: '评分',
  overall: '总分',

  // —— 改名投票
  nameVoteTitle: '这地方叫什么',
  nameVoteHint: '一人一票，票高者胜',
  nameProposeNew: '起个名',
  namePlaceholder: '起个所有人都认得出的名字',
  nameSubmit: '提交',
  voteFailed: '没投上，再试一次',
  nameTooFast: '慢一点，一小时最多提 10 个名字',

  // —— 报新厕所
  addToilet: '报个新厕所',
  addToiletTitle: '这儿有个厕所',
  pinHint: '拖动地图，把十字对准厕所门口',
  pinConfirm: '就是这里',
  pinRetake: '重新选位置',
  addName: '叫什么',
  addNamePlaceholder: '比如：星巴克三楼、地铁站 B 口',
  addAddress: '地址（可选）',
  addAddressPlaceholder: '写个路口或楼名就够',
  addCategory: '什么场所',
  addSubmit: '提交',
  addSubmitting: '提交中…',
  addDone: '收到，已经在地图上了',
  addFailed: '没提交上去，再试一次',
  addNeedName: '给它起个名字',
  addTooFast: '慢一点，一小时最多报 5 个',
  catPublic: '公共厕所',
  catMall: '商场',
  catCampus: '校园',
  catRestaurant: '餐饮店',
  catTransit: '车站',
  catOffice: '写字楼',
  catPark: '公园',
  catOther: '其它',

  // —— 设施墙
  facilities: '设施',
  facPaper: '厕纸',
  facSoap: '洗手液',
  facDryer: '烘手机',
  facHook: '挂钩',
  facAccessible: '无障碍',
  facBaby: '婴儿台',
  facFree: '免费',
  facOpen24h: '24 小时',
  facNeedsCode: '需消费/密码',
  facSquat: '蹲便',
  facSeated: '坐便',
  facUnknown: '没人填',
  stallCount: (n: number) => `${n} 个隔间`,

  // —— 评分
  ratings: '评分',
  rateClean: '干净',
  rateSmell: '气味',
  rateQueue: '不用排',
  ratePrivacy: '私密',
  ratingHint: '5 分最好，1 分最惨',
  noRatingsYet: '还没人打过分',

  // —— 评价流
  reviews: '锐评',
  reviewCount: (n: number) => (n === 0 ? '还没有评价' : `${n} 条评价`),
  beFirst: '第一个来评的人，说不定能笑死后面所有人',
  aiBadge: 'AI 润色',
  seedBadge: '示例数据',
  editedBadge: '本人改过',
  anonymous: '匿名马桶侠',
  funnyUp: '好笑',
  funnyDown: '不好笑',
  funnyScore: '搞笑程度',
  funnyMode: '搞笑模式',
  discoverMode: '地图模式',
  featuredToilets: '今日神坑',
  featuredReviews: '高赞锐评',
  expandPanel: '展开面板',
  collapsePanel: '收起面板',
  loadingMore: '加载中…',

  // —— 写评价
  writeReview: '写条锐评',
  stepRate: '先打个分',
  stepTags: '发生了什么',
  stepStyle: '这条谁来写',
  stepPreview: '预览，可以改',
  rawNoteLabel: '想补一句？（可留空）',
  rawNotePlaceholder: '一句话就行，剩下的交给 AI',
  generate: '生成锐评',
  generating: '正在憋…',
  regenerate: '再来一条',
  rerollStyle: '换个文风',
  previewHint: '可以直接改。发布出去的就是你现在看到的这版。',
  publish: '发布',
  publishing: '发布中…',
  published: '发布成功',
  needGenerate: '先生成一条再发',
  generateFailed: '没生成出来，再试一次',
  rateLimited: '慢一点，一分钟最多 3 条',
  notLoggedIn: '正在给你开一个匿名号…',

  // —— 举报
  report: '举报',
  reportTitle: '举报这条评价',
  reasonOffensive: '内容不当',
  reasonFalseInfo: '信息不实',
  reasonSpam: '广告灌水',
  reasonPrivacy: '涉及隐私',
  reasonOther: '其他',
  reportSubmitted: '收到了，谢谢',

  // —— 分享
  share: '生成分享图',
  shareTitle: '分享卡片',
  shareHint: '长按图片保存，或点下面的按钮下载',
  saveImage: '保存图片',
  shareGenerating: '正在画…',

  // —— 昵称
  nickname: '昵称',
  nicknamePlaceholder: '随便起一个',
  saveNickname: '存好了',

  // —— 通用
  back: '返回',
  close: '关闭',
  cancel: '取消',
  confirm: '确定',
  retry: '重试',
  loading: '加载中…',
  notFound: '没找到这个地方',

  // —— 设置 / 地区
  settings: '设置',
  language: '语言',
  region: '地图版本',
  regionCn: '国内版（高德）',
  regionIntl: '海外版',
  regionHint: '国内版用高德瓦片并做 GCJ-02 偏移，在中国大陆用这个',
  regionSwitchReload: '切换后地图会重新加载',

  // —— 各种没配置好的状态
  dbNotConfigured: '还没连上数据库',
  dbNotConfiguredHint: '把 .env.local 里的 Supabase 地址和 anon key 填上',
  intlTilesMissing: '海外底图没配 key，只显示标记点',

  // —— 单位
  meters: (m: number) => (m < 1000 ? `${Math.round(m)} 米` : `${(m / 1000).toFixed(1)} 公里`),
  justNow: '刚刚',
  minutesAgo: (n: number) => `${n} 分钟前`,
  hoursAgo: (n: number) => `${n} 小时前`,
  daysAgo: (n: number) => `${n} 天前`,
}

type Dict = typeof zh

const en: Dict = {
  appName: 'pooping',
  appNameLatin: 'pooping',
  tagline: 'Yelp, but for toilets',
  domain: 'pooping.me',

  nearby: 'Toilets nearby',
  locating: 'Finding you…',
  locationDenied: "Couldn't get your location — here's a default spot",
  searchThisArea: 'Search this area',
  recenter: 'Back to me',
  noResults: 'No toilets mapped around here yet',
  noResultsHint: 'Zoom out a bit, or drop a filter or two',
  resultCount: (n: number) => `${n} ${n === 1 ? 'spot' : 'spots'}`,
  listView: 'List',
  mapView: 'Map',

  filters: 'Filters',
  filterHasPaper: 'Has paper',
  filterFree: 'Free',
  filterAccessible: 'Accessible',
  filterSeated: 'Seated',
  clearFilters: 'Clear',

  viewDetail: 'View details',
  tagsOther: 'More',

  modeSelf: 'Write it myself',
  selfWriteLabel: 'Say your piece',
  selfWritePlaceholder: 'Straight from you, no AI involved',
  selfWriteHint: 'No AI involved, and no AI badge',
  needSelfText: 'Nothing written yet',
  humanBadge: 'Hand-written',
  tagCount: (n: number, max: number) => `${n}/${max} picked`,
  tagLimitNote: "the single-choice rows don't count",
  sortLabel: 'Sort',
  sortDistance: 'Distance',
  sortRating: 'Rating',
  overall: 'Overall',

  nameVoteTitle: 'What is this place called',
  nameVoteHint: 'one vote each, top name wins',
  nameProposeNew: 'Name it',
  namePlaceholder: 'Something everyone would recognise',
  nameSubmit: 'Submit',
  voteFailed: "That didn't register. Try again.",
  nameTooFast: 'Slow down — 10 name ideas per hour',

  addToilet: 'Add a toilet',
  addToiletTitle: "There's a toilet here",
  pinHint: 'Drag the map to put the crosshair on the door',
  pinConfirm: 'Use this spot',
  pinRetake: 'Move the pin',
  addName: 'What is it called',
  addNamePlaceholder: 'e.g. Starbucks 3rd floor, Exit B',
  addAddressPlaceholder: 'A cross street or building name is plenty',
  addAddress: 'Address (optional)',
  addCategory: 'What kind of place',
  addSubmit: 'Submit',
  addSubmitting: 'Submitting…',
  addDone: 'Got it — it is on the map',
  addFailed: "That didn't go through. Try again.",
  addNeedName: 'Give it a name first',
  addTooFast: 'Slow down — 5 new spots per hour',
  catPublic: 'Public',
  catMall: 'Mall',
  catCampus: 'Campus',
  catRestaurant: 'Restaurant',
  catTransit: 'Transit',
  catOffice: 'Office',
  catPark: 'Park',
  catOther: 'Other',

  facilities: 'Facilities',
  facPaper: 'Paper',
  facSoap: 'Soap',
  facDryer: 'Hand dryer',
  facHook: 'Hook',
  facAccessible: 'Accessible',
  facBaby: 'Baby table',
  facFree: 'Free',
  facOpen24h: 'Open 24h',
  facNeedsCode: 'Code / purchase',
  facSquat: 'Squat',
  facSeated: 'Seated',
  facUnknown: 'Nobody said',
  stallCount: (n: number) => `${n} ${n === 1 ? 'stall' : 'stalls'}`,

  ratings: 'Ratings',
  rateClean: 'Clean',
  rateSmell: 'Smell',
  rateQueue: 'No wait',
  ratePrivacy: 'Privacy',
  ratingHint: '5 is great, 1 is a war story',
  noRatingsYet: 'Nobody has rated this yet',

  reviews: 'Reviews',
  reviewCount: (n: number) => (n === 0 ? 'No reviews yet' : `${n} ${n === 1 ? 'review' : 'reviews'}`),
  beFirst: 'Go first. Set the tone. Ruin someone’s day in a fun way.',
  aiBadge: 'AI-polished',
  seedBadge: 'Sample',
  editedBadge: 'Edited by author',
  anonymous: 'Anonymous Flusher',
  funnyUp: 'Funny',
  funnyDown: 'Not funny',
  funnyScore: 'Funny score',
  funnyMode: 'Funny mode',
  discoverMode: 'Map mode',
  featuredToilets: 'Top stalls',
  featuredReviews: 'Top reviews',
  expandPanel: 'Expand panel',
  collapsePanel: 'Collapse panel',
  loadingMore: 'Loading…',

  writeReview: 'Write a review',
  stepRate: 'Rate it',
  stepTags: 'What happened',
  stepStyle: 'Who writes this one',
  stepPreview: 'Preview — edit freely',
  rawNoteLabel: 'Anything to add? (optional)',
  rawNotePlaceholder: 'One line is plenty. The AI does the rest.',
  generate: 'Generate',
  generating: 'Straining…',
  regenerate: 'Another one',
  rerollStyle: 'Different voice',
  previewHint: 'Edit it however you like. What you see is exactly what gets published.',
  publish: 'Publish',
  publishing: 'Publishing…',
  published: 'Published',
  needGenerate: 'Generate something first',
  generateFailed: "That didn't come out. Try again.",
  rateLimited: 'Slow down — 3 reviews per minute',
  notLoggedIn: 'Setting up an anonymous account…',

  report: 'Report',
  reportTitle: 'Report this review',
  reasonOffensive: 'Offensive',
  reasonFalseInfo: 'Wrong information',
  reasonSpam: 'Spam',
  reasonPrivacy: 'Privacy issue',
  reasonOther: 'Other',
  reportSubmitted: 'Got it, thanks',

  share: 'Make share card',
  shareTitle: 'Share card',
  shareHint: 'Long-press to save, or hit the button below',
  saveImage: 'Save image',
  shareGenerating: 'Drawing…',

  nickname: 'Nickname',
  nicknamePlaceholder: 'Anything works',
  saveNickname: 'Saved',

  back: 'Back',
  close: 'Close',
  cancel: 'Cancel',
  confirm: 'OK',
  retry: 'Retry',
  loading: 'Loading…',
  notFound: "Couldn't find that place",

  settings: 'Settings',
  language: 'Language',
  region: 'Map version',
  regionCn: 'China (AutoNavi)',
  regionIntl: 'International',
  regionHint: 'China mode uses AutoNavi tiles with GCJ-02 offset. Use it inside mainland China.',
  regionSwitchReload: 'The map reloads after switching',

  dbNotConfigured: 'Database not connected',
  dbNotConfiguredHint: 'Fill in the Supabase URL and anon key in .env.local',
  intlTilesMissing: 'No international tile key configured — markers only',

  meters: (m: number) => (m < 1000 ? `${Math.round(m)} m` : `${(m / 1000).toFixed(1)} km`),
  justNow: 'just now',
  minutesAgo: (n: number) => `${n}m ago`,
  hoursAgo: (n: number) => `${n}h ago`,
  daysAgo: (n: number) => `${n}d ago`,
}

export const COPY: Record<Locale, Dict> = { zh, en }
export type Copy = Dict
